services:
  app:
    ports:
      - "7800:7800"
    build:
      dockerfile: dockerfile
      context: app
    image: dbop/app
    container_name: dbopapp
    depends_on:
      - db
    networks:
      - "test-network"
    volumes:
      - "./app/build:/opt/app/build"

  db:
    ports:
      - "3306:3306"
    build:
      dockerfile: dockerfile
      context: database
    image: dbop/db
    container_name: dbopdb
    environment:
      MYSQL_ROOT_PASSWORD: letmein12345
      MYSQL_DATABASE: dbop
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-pletmein12345",
        ]
      interval: 8s
      retries: 8
      start_period: 10s
      timeout: 15s
    networks:
      - "test-network"
    volumes:
      - ./data/mysql:/var/lib/mysql

  memdb:
    image: redis:7.2
    container_name: dbopmemdb
    ports:
      - "6379:6379"
    networks:
      - "test-network"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  ### SETUP FOR MONITORING

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - "test-network"
    volumes:
      - ./data/grafana:/var/lib/grafana

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.46.0
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - test-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
